[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.12.1 --activate",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
